#!/usr/bin/env bash
# Generated by esper:init. Commands are project-specific and static.
FAILED=0

echo "--- esper: lint ---"
bun run lint
[ $? -ne 0 ] && FAILED=1

echo "--- esper: typecheck ---"
bun run typecheck
[ $? -ne 0 ] && FAILED=1

if [ $FAILED -ne 0 ]; then
  echo ""
  echo "esper: verification failed — fix the errors above before continuing."
fi

exit 0
