import type { ProviderConfig, ModelConfig } from "../router/types.js";

export interface Identity {
  name: string;
  personality: string;
  systemPrompt: string;
}

export interface RuntimeConfig {
  activeModel: string;
  telegramBotTokenEnvVar: string;
  memory: {
    enabled: boolean;
    directory: string;
  };
}

/** On-disk config.json schema (v3 — merged models + runtime) */
export interface SAConfigFile {
  version: 3;
  runtime: RuntimeConfig;
  providers: ProviderConfig[];
  models: ModelConfig[];
  defaultModel: string;
}

/** Full in-memory config (identity from IDENTITY.md + everything else from config.json) */
export interface SAConfig {
  identity: Identity;
  runtime: RuntimeConfig;
  providers: ProviderConfig[];
  models: ModelConfig[];
  defaultModel: string;
}

export interface SecretsFile {
  /** Map of env var name → raw API key, e.g. { "ANTHROPIC_API_KEY": "sk-..." } */
  apiKeys: Record<string, string>;
  /** Raw Telegram bot token, if stored */
  botToken?: string;
  /** Telegram chat ID of the paired user — bot ignores all other senders */
  pairedChatId?: number;
  /** One-time pairing code generated by the wizard; user sends /pair <code> to activate filtering */
  pairingCode?: string;
  /** Raw Discord bot token, if stored */
  discordToken?: string;
  /** Discord guild (server) ID for bot operation */
  discordGuildId?: string;
}
