import { Bot, type Context } from "grammy";
import type { Agent } from "../agent/index.js";
import { splitMessage, formatToolResult } from "./formatter.js";

const EDIT_THROTTLE_MS = 1000;

export interface TelegramTransportOptions {
  botToken: string;
  agent: Agent;
  allowedChatId?: number;
  /** Pairing code generated by the wizard; enables /pair <code> command */
  pairingCode?: string;
  /** Called when a user successfully pairs — persist the chat ID to secrets */
  onPaired?: (chatId: number) => Promise<void>;
}

/** Pure helper — returns true if the message is from an allowed sender */
export function isMessageAllowed(allowedChatId: number | undefined, chatId: number): boolean {
  return allowedChatId === undefined || allowedChatId === chatId;
}

/** Pure helper — validates that the user-supplied pairing code matches the expected one */
export function validatePairingCode(input: string | undefined, expected: string | undefined): boolean {
  if (!expected || !input) return false;
  return input.trim().toUpperCase() === expected.toUpperCase();
}

export class TelegramTransport {
  private bot: Bot;
  private agent: Agent;
  private allowedChatId?: number;
  private pairingCode?: string;
  private onPaired?: (chatId: number) => Promise<void>;

  constructor(options: TelegramTransportOptions) {
    this.bot = new Bot(options.botToken);
    this.agent = options.agent;
    this.allowedChatId = options.allowedChatId;
    this.pairingCode = options.pairingCode;
    this.onPaired = options.onPaired;
    this.setupHandlers();
  }

  private async handlePairCommand(ctx: Context): Promise<void> {
    if (!this.pairingCode) {
      await ctx.reply("❌ No pairing code configured. Run the setup wizard first.");
      return;
    }

    const parts = ctx.message?.text?.split(" ") ?? [];
    const supplied = parts[1];

    if (!supplied) {
      await ctx.reply("Usage: /pair <code>\nEnter the pairing code shown during setup.");
      return;
    }

    if (!validatePairingCode(supplied, this.pairingCode)) {
      await ctx.reply("❌ Invalid pairing code. Check the code shown during setup and try again.");
      return;
    }

    const chatId = ctx.message!.chat.id;
    this.allowedChatId = chatId;

    if (this.onPaired) {
      try {
        await this.onPaired(chatId);
      } catch (err) {
        console.error("Failed to persist paired chat ID:", err);
      }
    }

    await ctx.reply("✅ Paired! I will only respond to you from now on.");
  }

  private setupHandlers(): void {
    this.bot.on("message:text", async (ctx) => {
      const userText = ctx.message.text;

      // /pair command is exempt from allowedChatId filtering
      if (userText.startsWith("/pair")) {
        await this.handlePairCommand(ctx);
        return;
      }

      // Security: restrict to allowed chat ID
      if (!isMessageAllowed(this.allowedChatId, ctx.message.chat.id)) {
        return;
      }

      // Show typing indicator instead of sending a placeholder message
      await ctx.api.sendChatAction(ctx.message.chat.id, "typing");
      let sentMsg: Awaited<ReturnType<typeof ctx.reply>> | null = null;
      let fullText = "";
      let lastEditTime = 0;

      try {
        for await (const event of this.agent.chat(userText)) {
          switch (event.type) {
            case "text_delta":
              fullText += event.delta;
              // Throttle edits to avoid Telegram rate limits
              if (Date.now() - lastEditTime > EDIT_THROTTLE_MS && fullText.length > 0) {
                try {
                  if (!sentMsg) {
                    // First chunk — send as a new message
                    sentMsg = await ctx.reply(fullText.slice(0, 4096));
                  } else {
                    await ctx.api.editMessageText(
                      ctx.message.chat.id,
                      sentMsg.message_id,
                      fullText.slice(0, 4096)
                    );
                  }
                  lastEditTime = Date.now();
                } catch {
                  // Edit may fail if content unchanged — ignore
                }
              }
              break;

            case "tool_end": {
              const toolMsg = formatToolResult(event.name, event.result.content);
              try {
                await ctx.reply(toolMsg, { parse_mode: "MarkdownV2" });
              } catch {
                // Fallback to plain text if markdown fails
                await ctx.reply(`[${event.name}] ${event.result.content.slice(0, 500)}`);
              }
              break;
            }

            case "done":
              // Final message with complete text
              if (fullText) {
                const chunks = splitMessage(fullText);
                try {
                  if (!sentMsg) {
                    // Never sent a streaming message — send the final text directly
                    sentMsg = await ctx.reply(chunks[0]);
                  } else {
                    await ctx.api.editMessageText(
                      ctx.message.chat.id,
                      sentMsg.message_id,
                      chunks[0]
                    );
                  }
                } catch {
                  // ignore
                }
                // Send additional chunks as new messages
                for (let i = 1; i < chunks.length; i++) {
                  await ctx.reply(chunks[i]);
                }
              }
              break;

            case "error":
              await ctx.reply(`⚠️ Error: ${event.message}`);
              break;
          }
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        await ctx.reply(`⚠️ Error: ${msg}`);
      }
    });

    this.bot.catch((err) => {
      console.error("Telegram bot error:", err);
    });
  }

  async start(): Promise<void> {
    await this.bot.start({
      onStart: (botInfo) => {
        console.log(`Telegram bot @${botInfo.username} started`);
      },
    });
  }

  async stop(): Promise<void> {
    await this.bot.stop();
  }

  isRunning(): boolean {
    return this.bot.isRunning();
  }
}
